# Generated by Django 5.2.7 on 2025-11-09 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Analysis name", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Analysis description and goals"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "model_name",
                    models.CharField(
                        default="openai/clip-vit-base-patch32",
                        help_text="CLIP model used for analysis",
                        max_length=100,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for tracking",
                        max_length=255,
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0, help_text="Processing progress (0-100)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if analysis failed"
                    ),
                ),
                (
                    "images_processed",
                    models.IntegerField(
                        default=0, help_text="Number of images successfully processed"
                    ),
                ),
                (
                    "total_images",
                    models.IntegerField(
                        default=0, help_text="Total number of images to process"
                    ),
                ),
                (
                    "processing_time_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Total processing time in seconds",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="images.imagedataset",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analysis",
                "verbose_name_plural": "Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TextPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Text prompt or keyword", max_length=500
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_prompts",
                        to="analysis.analysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Text Prompt",
                "verbose_name_plural": "Text Prompts",
                "ordering": ["analysis", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SimilarityResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(help_text="CLIP similarity score (-1 to 1)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="analysis.analysis",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_results",
                        to="images.image",
                    ),
                ),
                (
                    "text_prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="analysis.textprompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Similarity Result",
                "verbose_name_plural": "Similarity Results",
            },
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                fields=["project", "-created_at"], name="analysis_an_project_789b05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                fields=["status", "-created_at"], name="analysis_an_status_b5ea0c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="textprompt",
            unique_together={("analysis", "text")},
        ),
        migrations.AddIndex(
            model_name="similarityresult",
            index=models.Index(
                fields=["analysis", "similarity_score"],
                name="analysis_si_analysi_27e0a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="similarityresult",
            index=models.Index(
                fields=["text_prompt", "similarity_score"],
                name="analysis_si_text_pr_e47282_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="similarityresult",
            index=models.Index(
                fields=["image", "analysis"], name="analysis_si_image_i_fc1f48_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="similarityresult",
            unique_together={("analysis", "image", "text_prompt")},
        ),
    ]
