# Generated by Django 5.2.7 on 2025-11-09 10:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Dataset name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Dataset description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Dataset",
                "verbose_name_plural": "Image Datasets",
                "ordering": ["-created_at"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        upload_to="uploads/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="thumbnails/%Y/%m/%d/"
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                (
                    "format",
                    models.CharField(
                        help_text="Image format (JPEG, PNG, etc.)", max_length=10
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="images.imagedataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ImageMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exif_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Full EXIF data from image"
                    ),
                ),
                (
                    "has_gps",
                    models.BooleanField(
                        default=False, help_text="Whether image contains GPS data"
                    ),
                ),
                ("camera_make", models.CharField(blank=True, max_length=100)),
                ("camera_model", models.CharField(blank=True, max_length=100)),
                (
                    "date_taken",
                    models.DateTimeField(
                        blank=True,
                        help_text="Original date/time photo was taken",
                        null=True,
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="images.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Metadata",
                "verbose_name_plural": "Image Metadata",
            },
        ),
        migrations.CreateModel(
            name="GPSData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, help_text="GPS latitude", max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, help_text="GPS longitude", max_digits=9
                    ),
                ),
                (
                    "altitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="GPS altitude in meters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "location_tag",
                    models.CharField(
                        blank=True, help_text="Named location or tag", max_length=255
                    ),
                ),
                (
                    "normalized_latitude",
                    models.FloatField(
                        blank=True,
                        help_text="Normalized latitude (0-1 scale)",
                        null=True,
                    ),
                ),
                (
                    "normalized_longitude",
                    models.FloatField(
                        blank=True,
                        help_text="Normalized longitude (0-1 scale)",
                        null=True,
                    ),
                ),
                (
                    "location_cluster",
                    models.IntegerField(
                        blank=True,
                        help_text="Location cluster ID from KMeans",
                        null=True,
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_data",
                        to="images.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "GPS Data",
                "verbose_name_plural": "GPS Data",
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="images_gpsd_latitud_bba4cd_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["dataset", "-uploaded_at"],
                name="images_imag_dataset_e392dd_idx",
            ),
        ),
    ]
