# Generated by Django 5.2.7 on 2025-11-09 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("csv", "CSV"),
                            ("zip", "ZIP Archive"),
                            ("pdf", "PDF Report"),
                            ("excel", "Excel Spreadsheet"),
                        ],
                        help_text="Export format",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to generated export file",
                        max_length=500,
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "include_images",
                    models.BooleanField(
                        default=False, help_text="Include original images in export"
                    ),
                ),
                (
                    "include_visualizations",
                    models.BooleanField(
                        default=True, help_text="Include visualizations in export"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for tracking",
                        max_length=255,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if export failed"
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="analysis.analysis",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Job",
                "verbose_name_plural": "Export Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Visualization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viz_type",
                    models.CharField(
                        choices=[
                            ("heatmap", "Similarity Heatmap"),
                            ("map", "GPS Map"),
                            ("correlation", "Correlation Matrix"),
                            ("violin", "Violin Plot"),
                            ("location_corr", "Location Correlation"),
                            ("image_grid", "Image Grid"),
                            ("bar_chart", "Bar Chart"),
                            ("scatter", "Scatter Plot"),
                        ],
                        help_text="Type of visualization",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Visualization title", max_length=255),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Path to generated file", max_length=500
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        default="png",
                        help_text="File format (png, html, svg, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Visualization-specific parameters",
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualizations",
                        to="analysis.analysis",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_visualizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Visualization",
                "verbose_name_plural": "Visualizations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["analysis", "-created_at"],
                        name="visualizati_analysi_a2861b_idx",
                    ),
                    models.Index(
                        fields=["viz_type"], name="visualizati_viz_typ_f71d14_idx"
                    ),
                ],
            },
        ),
    ]
